# This is the SAM template for deploying the lambdas.
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for deploying all lambdas
Parameters: 
  Author:
    Type: String
    Description: Author of this Lambda.
  LambdaRoleArn:
    Type: String
    Description: Lambda role ARN to be used for all lambdas
  StateMachineARN:
    Type: String
    Description: Lambda role ARN to be used for all lambdas
Resources:
  myapp_get_data:
    Type: AWS::Serverless::Function
    Properties:
      Handler: myapp_get_data.lambda_handler
      Runtime: Python3.8
      CodeUri: ../../python_lambda/myapp_get_data.py
      Role: !Ref LambdaRoleArn
      FunctionName: myapp_get_data
      Timeout: 120
      MemorySize: 128
      Environment:
        Variables:
          Author: !Ref Author
      Tags:
        project: aws-serverless
        type: lambda
  